/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#d0bcff',
        'on-surface': '#e7e0ed',
        'border-purple': 'rgba(139, 92, 246, 0.2)',
        'background': '#15121b',
        'orb-purple': 'rgba(139, 92, 246, 0.15)',
        'orb-blue': 'rgba(59, 130, 246, 0.1)',
        'primary': '#d0bcff',
        'primary-container': '#a078ff',
        'on-primary': '#3c0091',
        'secondary': '#adc6ff',
        'secondary-container': '#0566d9',
        'tertiary': '#ffb869',
        'tertiary-container': '#ca801e',
        'text-secondary': 'rgba(255, 255, 255, 0.7)',
        'text-low-emphasis': 'rgba(255, 255, 255, 0.4)',
        'divider': 'rgba(255, 255, 255, 0.06)',
        'surface-glass': 'rgba(255, 255, 255, 0.04)',
        'background-page': '#0a0a14',
        'surface': '#15121b',
        'surface-dim': '#15121b',
      },
      fontFamily: {
        'display-hero': ['Inter'],
        'headline-section': ['Inter'],
        'headline-card': ['Inter'],
        'body-md': ['Inter'],
        'label-navigation': ['Inter'],
        'caption': ['Inter'],
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-section': ['40px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-card': ['24px', { lineHeight: '1.2', letterSpacing: '0', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'label-navigation': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '600' }],
        'caption': ['12px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
      },
      spacing: {
        'section-padding-v': '90px',
        'container-max': '1200px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'card-padding': '2rem',
      },
      maxWidth: {
        'container-max': '1200px',
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
}
